# Default configuration for testing

cvpath: "outputs/YYYY-MM-DD/HH-MM-SS" # Placeholder: Path to the trained model's cross-validation output directory (outputs from a train_crossval.py run)
# Users should override this with the actual path to their training outputs.
# Example: outputs/2023-10-27/12-34-56 (if Hydra multirun was used for training)
# Or: results/some_experiment_id (if a custom path was used)

checkpoints:
  - "best_val_loss.pt"
  - "terminal.pt"

batch_size: 64
num_workers: 4
device_id: 0 # GPU device ID, 0 for first GPU.
