# Default configuration for testing

cvpath: "." # Special value: "latest" to find the most recent run in cfg.runs_path, or provide a specific path.
# Example specific path: "results/2023-10-27-12-34-56" (relative to Repo/ if running from Repo/)
# The script will look for fold subdirectories (1, 2, 3, etc.) inside this path.

checkpoints:
  - "best_val_loss.pt"
  - "terminal.pt"

batch_size: 64
num_workers: 4
device_id: 0 # GPU device ID, 0 for first GPU.
